'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Bus
    Public Property BusID As Integer
    Public Property BusNumber As String
    Public Property BusModel As String
    Public Property Capacity As Nullable(Of Integer)
    Public Property PurchaseDate As Nullable(Of Date)
    Public Property Status As String
    Public Property MaintenanceSchedule As Nullable(Of Date)

    Public Overridable Property BusAssignments As ICollection(Of BusAssignment) = New HashSet(Of BusAssignment)
    Public Overridable Property Feedbacks As ICollection(Of Feedback) = New HashSet(Of Feedback)
    Public Overridable Property MaintenanceRecords As ICollection(Of MaintenanceRecord) = New HashSet(Of MaintenanceRecord)
    Public Overridable Property Schedules As ICollection(Of Schedule) = New HashSet(Of Schedule)

End Class
