'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class BusAssignment
    Public Property AssignmentID As Integer
    Public Property BusID As Nullable(Of Integer)
    Public Property DriverID As Nullable(Of Integer)
    Public Property AssignmentDate As Nullable(Of Date)
    Public Property Shift As String

    Public Overridable Property Bus As Bus
    Public Overridable Property Driver As Driver

End Class
