'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Complaint
    Public Property ComplaintID As Integer
    Public Property PassengerID As Nullable(Of Integer)
    Public Property ComplaintDate As Nullable(Of Date)
    Public Property Description As String
    Public Property Status As String
    Public Property ResolutionDate As Nullable(Of Date)

    Public Overridable Property Passenger As Passenger

End Class
