'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Driver
    Public Property DriverID As Integer
    Public Property Name As String
    Public Property LicenseNumber As String
    Public Property ContactInfo As String
    Public Property HireDate As Nullable(Of Date)
    Public Property Experience As String
    Public Property ShiftDetails As String

    Public Overridable Property BusAssignments As ICollection(Of BusAssignment) = New HashSet(Of BusAssignment)

End Class
