'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Feedback
    Public Property FeedbackID As Integer
    Public Property PassengerID As Nullable(Of Integer)
    Public Property BusID As Nullable(Of Integer)
    Public Property RouteID As Nullable(Of Integer)
    Public Property FeedbackDate As Nullable(Of Date)
    Public Property Comments As String
    Public Property Rating As Nullable(Of Integer)

    Public Overridable Property Bus As Bus
    Public Overridable Property Passenger As Passenger
    Public Overridable Property Route As Route

End Class
