'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MaintenanceRecord
    Public Property MaintenanceID As Integer
    Public Property FormattedID As String
    Public Property BusID As Nullable(Of Integer)
    Public Property MaintenanceDate As Nullable(Of Date)
    Public Property Description As String
    Public Property Cost As Nullable(Of Decimal)
    Public Property ServiceCenter As String
    Public Property NextScheduledMaintenance As Nullable(Of Date)

    Public Overridable Property Bus As Bus

End Class
