'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class dbEntities1
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=dbEntities1")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property BusAssignments() As DbSet(Of BusAssignment)
    Public Overridable Property Buses() As DbSet(Of Bus)
    Public Overridable Property Complaints() As DbSet(Of Complaint)
    Public Overridable Property Drivers() As DbSet(Of Driver)
    Public Overridable Property Feedbacks() As DbSet(Of Feedback)
    Public Overridable Property MaintenanceRecords() As DbSet(Of MaintenanceRecord)
    Public Overridable Property Passengers() As DbSet(Of Passenger)
    Public Overridable Property Payments() As DbSet(Of Payment)
    Public Overridable Property Routes() As DbSet(Of Route)
    Public Overridable Property Schedules() As DbSet(Of Schedule)
    Public Overridable Property Stops() As DbSet(Of [Stop])
    Public Overridable Property Tickets() As DbSet(Of Ticket)

End Class
