'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Passenger
    Public Property PassengerID As Integer
    Public Property Name As String
    Public Property ContactInfo As String
    Public Property Address As String

    Public Overridable Property Complaints As ICollection(Of Complaint) = New HashSet(Of Complaint)
    Public Overridable Property Feedbacks As ICollection(Of Feedback) = New HashSet(Of Feedback)

End Class
