'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Route
    Public Property RouteID As Integer
    Public Property RouteName As String
    Public Property StartLocation As String
    Public Property EndLocation As String
    Public Property Distance As Nullable(Of Integer)
    Public Property Duration As String
    Public Property Stops As String

    Public Overridable Property Feedbacks As ICollection(Of Feedback) = New HashSet(Of Feedback)
    Public Overridable Property Schedules As ICollection(Of Schedule) = New HashSet(Of Schedule)
    Public Overridable Property Stops1 As ICollection(Of [Stop]) = New HashSet(Of [Stop])

End Class
