'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Schedule
    Public Property ScheduleID As Integer
    Public Property BusID As Nullable(Of Integer)
    Public Property RouteID As Nullable(Of Integer)
    Public Property DepartureTime As Nullable(Of System.TimeSpan)
    Public Property ArrivalTime As Nullable(Of System.TimeSpan)
    Public Property Frequency As String
    Public Property DaysOfOperation As String

    Public Overridable Property Bus As Bus
    Public Overridable Property Route As Route
    Public Overridable Property Tickets As ICollection(Of Ticket) = New HashSet(Of Ticket)

End Class
