//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMS.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ticket()
        {
            this.Payments = new HashSet<Payment>();
        }
    
        public int TicketID { get; set; }
        public Nullable<int> ScheduleID { get; set; }
        public string PassengerName { get; set; }
        public Nullable<int> SeatNumber { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public Nullable<decimal> Fare { get; set; }
        public string TicketStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual Schedule Schedule { get; set; }
    }
}
