//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stop
    {
        public int StopID { get; set; }
        public Nullable<int> RouteID { get; set; }
        public string StopName { get; set; }
        public string Location { get; set; }
        public Nullable<System.TimeSpan> ArrivalTime { get; set; }
        public Nullable<System.TimeSpan> DepartureTime { get; set; }
    
        public virtual Route Route { get; set; }
    }
}
